### ISSUE TITLE
InvalidVersion

### ISSUE THREAD

**Issue by jx1100370217** [taishan1994/pytorch_bert_chinese_classification#5]
D:\software\Anaconda3\envs\jx-sylas\python.exe E:\code\pytorch_bert_chinese_text_classification\main.py 
Traceback (most recent call last):
  File "E:\code\pytorch_bert_chinese_text_classification\main.py", line 20, in <module>
    from transformers import BertTokenizer
  File "D:\software\Anaconda3\envs\jx-sylas\lib\site-packages\transformers\__init__.py", line 43, in <module>
    from . import dependency_versions_check
  File "D:\software\Anaconda3\envs\jx-sylas\lib\site-packages\transformers\dependency_versions_check.py", line 41, in <module>
    require_version_core(deps[pkg])
  File "D:\software\Anaconda3\envs\jx-sylas\lib\site-packages\transformers\utils\versions.py", line 101, in require_version_core
    return require_version(requirement, hint)
  File "D:\software\Anaconda3\envs\jx-sylas\lib\site-packages\transformers\utils\versions.py", line 92, in require_version
    if want_ver is not None and not ops[op](version.parse(got_ver), version.parse(want_ver)):
  File "D:\software\Anaconda3\envs\jx-sylas\lib\site-packages\packaging\version.py", line 54, in parse
    return Version(version)
  File "D:\software\Anaconda3\envs\jx-sylas\lib\site-packages\packaging\version.py", line 200, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '0.10.1,<0.11'

**Comment by taishan1994** [comment]
pip install packaging==21.3 -i https://pypi.tuna.tsinghua.edu.cn/simple/
